"""
Pydantic Models for Meeting Intelligence Service

Completed models with all required fields.
"""

from pydantic import BaseModel
from typing import Optional, List


class User(BaseModel):
    """User model"""
    id: str
    name: str
    email: str
    role: str


class Contact(BaseModel):
    """External contact model"""
    id: str
    name: str
    email: str
    company: str
    role: str


class Meeting(BaseModel):
    """Meeting model"""
    id: str
    user_id: str
    contact_id: Optional[str] = None  # None for internal meetings
    title: str
    scheduled_date: str  # Format: YYYY-MM-DDTHH:MM:SS
    created_at: Optional[str] = None
    transcript: Optional[str] = None
    summary: Optional[str] = None
    action_items: List[str] = []
    sentiment: Optional[str] = None
    prep: Optional[str] = None  # Pre-meeting preparation text generated by LLM


class CreateMeetingRequest(BaseModel):
    """Request model for creating a meeting"""
    user_id: str
    contact_id: Optional[str] = None
    title: str
    scheduled_date: str  # Format: YYYY-MM-DDTHH:MM:SS


class TimeSlot(BaseModel):
    """Represents an available time slot"""
    start_time: str  # Format: YYYY-MM-DDTHH:MM:SS
    end_time: str    # Format: YYYY-MM-DDTHH:MM:SS


class PreMeetingPrep(BaseModel):
    """Pre-meeting preparation materials"""
    meeting_id: str
    prep_text: str
